---
- name: Install Image (Glance) Service
  hosts: imageservers
  sudo: yes

  tasks:
      - name: Create Glance database
        mysql_db: login_user=root login_password={{ MYSQL_ROOT }} name=glance state=present

      - name: Create Glance database user
        mysql_user: login_user=root login_password={{ MYSQL_ROOT }} host={{ inventory_hostname }} name=glance password={{ GLANCE_DBPASS }} priv=glance.*:ALL state=present

      - name: Create Glance Service Credentials
        command: openstack user create --password={{ GLANCE_PASS }} glance

      - name: Install Glance
        apt: name={{ item }} state=present update_cache=yes cache_valid_time=3600
        with_items:
          - glance
          - python-glanceclient

      - name: Generate Glance API Config
        template: src=files/glance-api.conf.j2 dest=/etc/glance/glance-api.conf owner=glance group=glance mode=0644

      - name: Generate Glance Registry Config
        template: src=files/glance-registry.conf.j2 dest=/etc/glance/glance-api.conf owner=glance group=glance mode=0644

      - name: Create OpenStack Glance Service
        shell: OS_URL=http://localhost:35357/v2.0 OS_TOKEN={{ KEYSTONE_DBPASS }} openstack service create --name glance --description "OpenStack Image Service" image

      - name: Create OpenStack Glance Endpoint
        shell: OS_URL=http://localhost:35357/v2.0 OS_TOKEN={{ KEYSTONE_DBPASS }} openstack endpoint create --publicurl http://localhost:9292/v2.0 --internalurl http://localhost:9292/v2.0 --adminurl http://localhost:9292/v2.0 --region RegionOne image
        ignore_errors: True

      - name: Populate the Glance Service Database
        command: /usr/bin/glance-manage db_sync

      - name: Restart Glance Registry Service
        service: name=glance-registry state=restarted

      - name: Restart Glance API Service
        service: name=glance-api state=restarted
