---
- name: Deploy MariaDB
  hosts: dbservers
  sudo: yes

  tasks:
    - name: Set default root password for MariaDB
      command: /usr/bin/debconf-set-selections <<< {{ item }}
      with_items:
          - 'mysql-server mysql-server/root_password password {{ MYSQL_ROOT }}'
          - 'mysql-server mysql-server/root_password_again password {{ MYSQL_ROOT }}'

    - name: Install MariaDB Service
      apt: name=mariadb-server state=present update_cache=yes cache_valid_time=3600

    - name: Create MariaDB conf.d directory
      file: dest=/etc/mysql/conf.d state=directory mode=0644

    - name: Set MariaDB Settings
      copy: src=files/mysqld_openstack.cnf dest=/etc/mysql/conf.d/mysqld_openstack.cnf mode=0644

    - name: Restart MariaDB Service
      service: name=mysql state=restarted

    - name: Install Python MySQLDB Driver
      apt: name=python-mysqldb state=present update_cache=yes cache_valid_time=3600

    - name: Drop TEST Database
      mysql_db: name=test state=absent login_user=root login_password={{ MYSQL_ROOT }}

    - name: Provision MariaDB Server
      command: /usr/bin/mysql -u root --password={{ MYSQL_ROOT }} -e "{{ item }}"
      ignore_errors: True
      with_items:
          - DELETE FROM mysql.user WHERE User='root' AND Host NOT IN ('localhost', '127.0.0.1', '::1');
          - DELETE FROM mysql.user WHERE User='';
          - FLUSH PRIVILEGES;
