---
- name: Install Networking (Nova) Service
  hosts: computenodes
  sudo: yes

  tasks:
    - name: Install Compute Node Packages
      apt: name={{ item }} state=present update_cache=yes cache_valid_time=3600
      with_items:
        - nova-network
        - nova-api-metadata

    - name: Restart Nova Services
      service: name={{ item }} state=restarted
      with_items:
        - nova-compute
