---
- name: Install Orchestration (Heat) Service
  hosts: heatnodes
  sudo: yes

 tasks:
     - name: Create Heat database
       mysql_db: login_user=root login_password={{ MYSQL_ROOT }} name=heat state=present

     - name: Create Heat database user for localhost
       mysql_user: login_user=root login_password={{ MYSQL_ROOT }} host=localhost name=heat password={{ HEAT_DBPASS }} priv=heat.*:ALL state=present
       
